version: "3"

services:
  frontend:
    build:
      context: "frontend"
    ports:
      - "8000:3000"
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: "backend"
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
